service: serverless-dev

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  vpc:
     securityGroupIds:
       - sg-01d6d6d10e996cde7
     subnetIds:
       - subnet-000315d04cabb21a4
       - subnet-099d371e047a1085d
       - subnet-0cfca41baccf57006
  layers:
      - arn:aws:lambda:us-east-1:751743882368:layer:tenjin-utils:3
  timeout: 10 # seconds
  memorySize: 128 # mb
  

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!yarn.lock"
    - "!package-lock.json"
    - "!package.json"
    - "!handler/**"

functions:
  test_new1:
    name: test_lambda_func_1
    handler: handler/lambda_function_one.lambda_handler
    package:
      patterns:
        - "handler/lambda_function_one.py"
  
  test_new2:
    name: test_lambda_func_2
    handler: handler/lambda_function_two.lambda_handler
    package:
      patterns:
        - "handler/lambda_function_two.py"
   
    
